name: fmu-config

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  pull_request:
    branches:
      - main

jobs:
  fmu-config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Checkout commit locally
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip install ".[dev]"

      - name: List all installed packages
        run: pip freeze

      - name: Lint with isort
        if: ${{ always() }}
        run: isort --check-only --profile black src tests

      - name: Lint with black
        if: ${{ always() }}
        run: black --check src tests

      - name: Lint with flake8
        if: ${{ always() }}
        run: flake8 src tests

      - name: Check typing with mypy
        if: ${{ always() }}
        run: mypy src

      - name: Run tests
        if: ${{ always() }}
        run: pytest tests

      - name: Syntax check documentation
        if: ${{ always() }}
        run: rstcheck -r docs

      - name: Build documentation
        if: ${{ always() }}
        run: sphinx-build -b html docs build/docs/html

      - name: Update GitHub pages
        if: github.repository_owner == 'equinor' && github.ref == 'refs/heads/main' && matrix.python-version == '3.8'
        run: |
          cp -R ./build/docs/html ../html

          git config --local user.email "fmu-config-github-action"
          git config --local user.name "fmu-config-github-action"
          git fetch origin gh-pages
          git checkout --track origin/gh-pages
          git clean -f -f -d -x  # Double -f is intentional
          git rm -r * --ignore-unmatch

          cp -R ../html/* .
          touch .nojekyll  # If not, github pages ignores _* directories.
          git add .

          if git diff-index --quiet HEAD; then
            echo "No changes in documentation. Skip documentation deploy."
          else
            git commit -m "Update Github Pages"
            git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
          fi
